In [4]:
import pandas as pd
import glob
import os

# Folder path
path = r"C:\sachin\Python\Daily Project\App_Ads_Analysis"

# Read all CSV files
all_files = glob.glob(os.path.join(path, "*.csv"))

# Combine all files
combined_list = []

for file in all_files:
    df = pd.read_csv(file)
    df['file_name'] = os.path.basename(file)

    # Extract app name safely
    parts = df['file_name'].iloc[0].split('_') if '_' in df['file_name'].iloc[0] else [df['file_name'].iloc[0]]
    app_name = parts[2].replace('.csv', '') if len(parts) > 2 else df['file_name'].iloc[0].replace('.csv', '')

    df['app'] = app_name
    df['ivt_status'] = 'IVT' if 'invalid' in file.lower() else 'Non-IVT'

    combined_list.append(df)

# Final combined dataframe
combined_data = pd.concat(combined_list, ignore_index=True)

# Quick check
print(combined_data[['app', 'ivt_status']].head())

    app ivt_status
0  data        IVT
1  data        IVT
2  data        IVT
3  data        IVT
4  data        IVT

In [10]:
combined_data.columns

Index(['date', 'unique_idfas', 'unique_ips', 'unique_uas', 'total_requests',
       'requests_per_idfa', 'impressions', 'impressions_per_idfa',
       'idfa_ip_ratio', 'idfa_ua_ratio', 'ivt', 'file_name', 'app',
       'ivt_status', 'Unnamed: 0', 'Unnamed: 1', 'Unnamed: 2', 'Unnamed: 3',
       'Unnamed: 4', 'Unnamed: 5', 'Unnamed: 6', 'Unnamed: 7', 'Unnamed: 8',
       'Unnamed: 9', 'Unnamed: 10', 'Unnamed: 11'],
      dtype='object')

In [9]:
combined_data.head(30)

,date,unique_idfas,unique_ips,unique_uas,total_requests,requests_per_idfa,impressions,impressions_per_idfa,idfa_ip_ratio,idfa_ua_ratio,...,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11
0,2025-09-11,91848.0,91830.0,232.0,97817.0,1.064988,0.0,0.0,1.000196,395.896552,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2025-09-12,376599.0,376351.0,268.0,480852.0,1.276828,0.0,0.0,1.000659,1405.220149,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2025-09-13,225317.0,225179.0,260.0,261039.0,1.158541,0.0,0.0,1.000613,866.603846,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2025-09-14,238368.0,238209.0,267.0,280450.0,1.176542,0.0,0.0,1.000667,892.764045,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2025-09-15,55073.0,55062.0,222.0,60235.0,1.093730,0.0,0.0,1.000200,248.076577,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,2025-09-11,26051.0,26049.0,774.0,27023.0,1.037311,0.0,0.0,1.000077,33.657623,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,2025-09-12,162095.0,161975.0,1174.0,194185.0,1.197970,0.0,0.0,1.000741,138.070698,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,2025-09-13,146191.0,146082.0,1171.0,165609.0,1.132826,0.0,0.0,1.000746,124.842869,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,2025-09-14,150568.0,150428.0,1232.0,171836.0,1.141252,0.0,0.0,1.000931,122.214286,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,2025-09-15,28822.0,28819.0,834.0,30555.0,1.060128,0.0,0.0,1.000104,34.558753,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,2025-09-11,92878.0,92548.0,210.0,126158.0,1.358320,0.0,0.0,1.003566,442.276190,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,2025-09-12,247402.0,245811.0,262.0,321354.0,1.298914,0.0,0.0,1.006472,944.282443,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,2025-09-13,223374.0,221963.0,252.0,280286.0,1.254783,0.0,0.0,1.006357,886.404762,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,2025-09-14,190510.0,189447.0,245.0,237432.0,1.246297,0.0,0.0,1.005611,777.591837,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,2025-09-15,21796.0,21785.0,182.0,23467.0,1.076665,0.0,0.0,1.000505,119.758242,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,2025-09-11,93345.0,93340.0,22.0,99280.0,1.063581,0.0,0.0,1.000054,4242.954545,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,2025-09-12,515646.0,515307.0,25.0,649515.0,1.259614,0.0,0.0,1.000658,20625.840000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,2025-09-13,406993.0,406729.0,25.0,473346.0,1.163032,0.0,0.0,1.000649,16279.720000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,2025-09-14,400917.0,400668.0,26.0,467152.0,1.165209,0.0,0.0,1.000621,15419.884620,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,2025-09-15,76526.0,76519.0,21.0,81409.0,1.063808,0.0,0.0,1.000091,3644.095238,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,2025-09-11,190487.0,187619.0,22.0,245116.0,1.286786,0.0,0.0,1.015286,8658.500000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21,2025-09-12,333653.0,325445.0,22.0,426365.0,1.277870,0.0,0.0,1.025221,15166.045450,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,2025-09-13,256525.0,251471.0,22.0,295879.0,1.153412,0.0,0.0,1.020098,11660.227270,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23,2025-09-14,255603.0,250533.0,22.0,307672.0,1.203710,0.0,0.0,1.020237,11618.318180,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24,2025-09-15,22684.0,22648.0,22.0,24175.0,1.065729,0.0,0.0,1.001590,1031.090909,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,2025-09-11 14:00:00,4163.0,4163.0,137.0,4219.0,1.013452,0.0,0.0,1.000000,30.386861,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26,2025-09-11 15:00:00,8317.0,8317.0,152.0,8433.0,1.013947,0.0,0.0,1.000000,54.717105,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,2025-09-11 16:00:00,13774.0,13774.0,166.0,14118.0,1.024975,0.0,0.0,1.000000,82.975904,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28,2025-09-11 17:00:00,11966.0,11966.0,164.0,12215.0,1.020809,0.0,0.0,1.000000,72.963415,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29,2025-09-11 18:00:00,7389.0,7389.0,132.0,7484.0,1.012857,0.0,0.0,1.000000,55.977273,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [11]:
combined_data = combined_data.loc[:, ~combined_data.columns.str.contains('^Unnamed')]

In [12]:
combined_data.duplicated().sum()

600

In [13]:
combined_data.isnull().sum()

date                    607
unique_idfas            606
unique_ips              606
unique_uas              606
total_requests          606
requests_per_idfa       606
impressions             606
impressions_per_idfa    606
idfa_ip_ratio           606
idfa_ua_ratio           606
ivt                     606
file_name                 0
app                       0
ivt_status                0
dtype: int64

In [16]:
combined_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1146 entries, 0 to 1145
Data columns (total 14 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   date                  539 non-null    object
 1   unique_idfas          540 non-null    float64
 2   unique_ips            540 non-null    float64
 3   unique_uas            540 non-null    float64
 4   total_requests        540 non-null    float64
 5   requests_per_idfa     540 non-null    float64
 6   impressions           540 non-null    float64
 7   impressions_per_idfa  540 non-null    float64
 8   idfa_ip_ratio         540 non-null    float64
 9   idfa_ua_ratio         540 non-null    float64
 10  ivt                   540 non-null    float64
 11  file_name             1146 non-null   object
 12  app                   1146 non-null   object
 13  ivt_status            1146 non-null   object
dtypes: float64(10), object(4)
memory usage: 125.5+ KB

In [19]:
combined_data.head(50)

,date,unique_idfas,unique_ips,unique_uas,total_requests,requests_per_idfa,impressions,impressions_per_idfa,idfa_ip_ratio,idfa_ua_ratio,ivt,file_name,app,ivt_status
0,2025-09-11,91848.0,91830.0,232.0,97817.0,1.064988,0.0,0.0,1.000196,395.896552,0.003532,clean_daily_data_invalid_1.csv,data,IVT
1,2025-09-12,376599.0,376351.0,268.0,480852.0,1.276828,0.0,0.0,1.000659,1405.220149,0.778107,clean_daily_data_invalid_1.csv,data,IVT
2,2025-09-13,225317.0,225179.0,260.0,261039.0,1.158541,0.0,0.0,1.000613,866.603846,0.994060,clean_daily_data_invalid_1.csv,data,IVT
3,2025-09-14,238368.0,238209.0,267.0,280450.0,1.176542,0.0,0.0,1.000667,892.764045,0.999405,clean_daily_data_invalid_1.csv,data,IVT
4,2025-09-15,55073.0,55062.0,222.0,60235.0,1.093730,0.0,0.0,1.000200,248.076577,1.000000,clean_daily_data_invalid_1.csv,data,IVT
5,2025-09-11,26051.0,26049.0,774.0,27023.0,1.037311,0.0,0.0,1.000077,33.657623,0.274060,clean_daily_data_invalid_2.csv,data,IVT
6,2025-09-12,162095.0,161975.0,1174.0,194185.0,1.197970,0.0,0.0,1.000741,138.070698,0.995055,clean_daily_data_invalid_2.csv,data,IVT
7,2025-09-13,146191.0,146082.0,1171.0,165609.0,1.132826,0.0,0.0,1.000746,124.842869,0.997219,clean_daily_data_invalid_2.csv,data,IVT
8,2025-09-14,150568.0,150428.0,1232.0,171836.0,1.141252,0.0,0.0,1.000931,122.214286,0.999106,clean_daily_data_invalid_2.csv,data,IVT
9,2025-09-15,28822.0,28819.0,834.0,30555.0,1.060128,0.0,0.0,1.000104,34.558753,1.000000,clean_daily_data_invalid_2.csv,data,IVT
10,2025-09-11,92878.0,92548.0,210.0,126158.0,1.358320,0.0,0.0,1.003566,442.276190,0.005292,clean_daily_data_invalid_3.csv,data,IVT
11,2025-09-12,247402.0,245811.0,262.0,321354.0,1.298914,0.0,0.0,1.006472,944.282443,0.005279,clean_daily_data_invalid_3.csv,data,IVT
12,2025-09-13,223374.0,221963.0,252.0,280286.0,1.254783,0.0,0.0,1.006357,886.404762,0.785315,clean_daily_data_invalid_3.csv,data,IVT
13,2025-09-14,190510.0,189447.0,245.0,237432.0,1.246297,0.0,0.0,1.005611,777.591837,0.997593,clean_daily_data_invalid_3.csv,data,IVT
14,2025-09-15,21796.0,21785.0,182.0,23467.0,1.076665,0.0,0.0,1.000505,119.758242,1.000000,clean_daily_data_invalid_3.csv,data,IVT
15,2025-09-11,93345.0,93340.0,22.0,99280.0,1.063581,0.0,0.0,1.000054,4242.954545,0.003456,clean_daily_data_valid_1.csv,data,Non-IVT
16,2025-09-12,515646.0,515307.0,25.0,649515.0,1.259614,0.0,0.0,1.000658,20625.840000,0.003409,clean_daily_data_valid_1.csv,data,Non-IVT
17,2025-09-13,406993.0,406729.0,25.0,473346.0,1.163032,0.0,0.0,1.000649,16279.720000,0.006033,clean_daily_data_valid_1.csv,data,Non-IVT
18,2025-09-14,400917.0,400668.0,26.0,467152.0,1.165209,0.0,0.0,1.000621,15419.884620,0.003836,clean_daily_data_valid_1.csv,data,Non-IVT
19,2025-09-15,76526.0,76519.0,21.0,81409.0,1.063808,0.0,0.0,1.000091,3644.095238,0.002968,clean_daily_data_valid_1.csv,data,Non-IVT
20,2025-09-11,190487.0,187619.0,22.0,245116.0,1.286786,0.0,0.0,1.015286,8658.500000,0.001874,clean_daily_data_valid_3.csv,data,Non-IVT
21,2025-09-12,333653.0,325445.0,22.0,426365.0,1.277870,0.0,0.0,1.025221,15166.045450,0.005005,clean_daily_data_valid_3.csv,data,Non-IVT
22,2025-09-13,256525.0,251471.0,22.0,295879.0,1.153412,0.0,0.0,1.020098,11660.227270,0.004753,clean_daily_data_valid_3.csv,data,Non-IVT
23,2025-09-14,255603.0,250533.0,22.0,307672.0,1.203710,0.0,0.0,1.020237,11618.318180,0.002864,clean_daily_data_valid_3.csv,data,Non-IVT
24,2025-09-15,22684.0,22648.0,22.0,24175.0,1.065729,0.0,0.0,1.001590,1031.090909,0.009282,clean_daily_data_valid_3.csv,data,Non-IVT
25,2025-09-11 14:00:00,4163.0,4163.0,137.0,4219.0,1.013452,0.0,0.0,1.000000,30.386861,0.000000,clean_hourly_data_invalid_1.csv,data,IVT
26,2025-09-11 15:00:00,8317.0,8317.0,152.0,8433.0,1.013947,0.0,0.0,1.000000,54.717105,0.000000,clean_hourly_data_invalid_1.csv,data,IVT
27,2025-09-11 16:00:00,13774.0,13774.0,166.0,14118.0,1.024975,0.0,0.0,1.000000,82.975904,0.000000,clean_hourly_data_invalid_1.csv,data,IVT
28,2025-09-11 17:00:00,11966.0,11966.0,164.0,12215.0,1.020809,0.0,0.0,1.000000,72.963415,0.000000,clean_hourly_data_invalid_1.csv,data,IVT
29,2025-09-11 18:00:00,7389.0,7389.0,132.0,7484.0,1.012857,0.0,0.0,1.000000,55.977273,0.025316,clean_hourly_data_invalid_1.csv,data,IVT
30,2025-09-11 19:00:00,8808.0,8808.0,140.0,8901.0,1.010559,0.0,0.0,1.000000,62.914286,0.000000,clean_hourly_data_invalid_1.csv,data,IVT
31,2025-09-11 20:00:00,11032.0,11032.0,148.0,11204.0,1.015591,0.0,0.0,1.000000,74.540541,0.000000,clean_hourly_data_invalid_1.csv,data,IVT
32,2025-09-11 21:00:00,9762.0,9762.0,151.0,9891.0,1.013215,0.0,0.0,1.000000,64.649007,0.000000,clean_hourly_data_invalid_1.csv,data,IVT
33,2025-09-11 22:00:00,11759.0,11758.0,151.0,11929.0,1.014457,0.0,0.0,1.000085,77.874172,0.010000,clean_hourly_data_invalid_1.csv,data,IVT
34,2025-09-11 23:00:00,9330.0,9330.0,150.0,9423.0,1.009968,0.0,0.0,1.000000,62.200000,0.000000,clean_hourly_data_invalid_1.csv,data,IVT
35,2025-09-12 00:00:00,9735.0,9735.0,146.0,9846.0,1.011402,0.0,0.0,1.000000,66.678082,0.000000,clean_hourly_data_invalid_1.csv,data,IVT
36,2025-09-12 01:00:00,5448.0,5448.0,141.0,5488.0,1.007342,0.0,0.0,1.000000,38.638298,0.000000,clean_hourly_data_invalid_1.csv,data,IVT
37,2025-09-12 02:00:00,5573.0,5572.0,147.0,5622.0,1.008792,0.0,0.0,1.000179,37.911565,0.000000,clean_hourly_data_invalid_1.csv,data,IVT
38,2025-09-12 03:00:00,10917.0,10916.0,168.0,11165.0,1.022717,0.0,0.0,1.000092,64.982143,0.007692,clean_hourly_data_invalid_1.csv,data,IVT
39,2025-09-12 04:00:00,6449.0,6449.0,152.0,6527.0,1.012095,0.0,0.0,1.000000,42.427632,0.126761,clean_hourly_data_invalid_1.csv,data,IVT
40,2025-09-12 05:00:00,5946.0,5946.0,157.0,6023.0,1.012950,0.0,0.0,1.000000,37.872611,0.620690,clean_hourly_data_invalid_1.csv,data,IVT
41,2025-09-12 06:00:00,6048.0,6046.0,162.0,6171.0,1.020337,0.0,0.0,1.000331,37.333333,1.000000,clean_hourly_data_invalid_1.csv,data,IVT
42,2025-09-12 07:00:00,8535.0,8535.0,192.0,8924.0,1.045577,0.0,0.0,1.000000,44.453125,1.000000,clean_hourly_data_invalid_1.csv,data,IVT
43,2025-09-12 08:00:00,7402.0,7402.0,179.0,7752.0,1.047285,0.0,0.0,1.000000,41.351955,1.000000,clean_hourly_data_invalid_1.csv,data,IVT
44,2025-09-12 09:00:00,8309.0,8308.0,176.0,8807.0,1.059935,0.0,0.0,1.000120,47.210227,0.989362,clean_hourly_data_invalid_1.csv,data,IVT
45,2025-09-12 10:00:00,9035.0,9035.0,176.0,9665.0,1.069729,0.0,0.0,1.000000,51.335227,0.975610,clean_hourly_data_invalid_1.csv,data,IVT
46,2025-09-12 11:00:00,8969.0,8968.0,189.0,9654.0,1.076374,0.0,0.0,1.000112,47.455026,0.990385,clean_hourly_data_invalid_1.csv,data,IVT
47,2025-09-12 12:00:00,9950.0,9948.0,193.0,10732.0,1.078593,0.0,0.0,1.000201,51.554404,1.000000,clean_hourly_data_invalid_1.csv,data,IVT
48,2025-09-12 13:00:00,13180.0,13180.0,197.0,14143.0,1.073065,0.0,0.0,1.000000,66.903553,1.000000,clean_hourly_data_invalid_1.csv,data,IVT
49,2025-09-12 14:00:00,20894.0,20892.0,187.0,22183.0,1.061692,0.0,0.0,1.000096,111.732620,1.000000,clean_hourly_data_invalid_1.csv,data,IVT

In [20]:
combined_data['app'].value_counts()

app
data         450
Invalid-1    101
Invalid-2    101
Invalid-3    101
Valid-1      101
Valid-2      101
Valid-3      101
clean         90
Name: count, dtype: int64